export const URL_LIST = 'https://api.themoviedb.org/3/discover/movie'
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query='
export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/'
export const URL_PERSON = 'https://api.themoviedb.org/3/person/'
export const URL_IMG = 'https://image.tmdb.org/t/p/'
export const URL_YOUTUBE = 'https://www.youtube.com/embed/'
export const URL_CAST = '/casts'
export const URL_VIDEO = '/videos'
export const IMG_SIZE_XSMALL = 'w45/'
export const IMG_SIZE_SMALL = 'w150/'
export const IMG_SIZE_LARGE = 'w342/'
export const CAST_MAX_NUM = 5
export const TRAILER_MAX_NUM = 3
export const API_KEY = '?api_key=ac3439121bf2a6cf27a1fa4d96625a41'
export const API_KEY_ALT = '&api_key=ac3439121bf2a6cf27a1fa4d96625a41'
export const URL_NETWORK = `https://api.themoviedb.org/3/discover/tv`
export const URL_TRND = `https://api.themoviedb.org/3/trending/all/week`
export const URL_UPCOMING = `https://api.themoviedb.org/3/movie/upcoming`
export const URL_GENRE = `https://api.themoviedb.org/3/genre/movie/list`
export const URL = 'https://api.themoviedb.org/3/'
export const API_PARAMS_GENRE = '&with_genres='
export const API_PARAMS_PAGE = '&page='
export const API_GET_MOVIE_POPULAR = 'movie/popular'
export const API_GET_MOVIE_UPCOMING = 'movie/upcoming'
export const API_GET_MOVIE_NOW_PLAYING = 'movie/now_playing'
export const API_GET_MOVIE_TOP_RATED = 'movie/top_rated'
export const API_GET_MOVIE_SIMILAR = (movieID: any) => `movie/${movieID}/similar`
